server:
  port: 9091

spring:
  profiles:
    active: dev #dev #local
  application:
    name: RESTAURANT-SERVICE
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

