spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_codedecode_restaurantDB
    username: root
    password: Metallica_911
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}